### ISSUE TITLE
Tracking Issues To Finish The Demo

### ISSUE THREAD

**Issue by 0xrjman** [Rustops/no-name-card-game#40]
# Tracking Issue

## Merged

- [x] #1
- [x] #4
- [x] #6
- [x] #10 
- [x] #12
- [x] #14
- [x] #17
- [x] #23 
- [x] #24
- [x] #27
- [x] #28
- [x] #32
- [x] #35

> Overall, we have roughly completed the basic functions needed to build the game, but we have not yet done the core part (the game), so I think the next step can be to start the game, in short, `Game Demo`

## Next

The successful binding of the avatar by the player entity means that the most important part needed to start the game is completed, because this is a PVP game and the user is the first.

- [ ] #36 
- [ ] game-mode(Game start mechanics，can be very easy)
- [ ] ready-to-start(game can start when enough players to ready)
- [ ] load-game-state(choose role and load default cards)
- [ ] ...
- [ ] What a demo should look like

**Comment by 0xrjman** [comment]
@hacpy , you can go through it and make changes that might not be appropriate
